version: "3.8"

services:
  db:
    container_name: contest_mode_db
    image: postgres:13.0-alpine
    env_file:
      - ./.env.prod
    networks:
      - "contest_backend"
    volumes:
      - contest_mode_db_vol:/var/lib/postgresql/data
      - ./import:/mnt/import
    environment:
      - POSTGRES_DB=${DB_NAME}
      - POSTGRES_USER=${DB_USERNAME}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
    expose:
      - ${DB_PORT}

  django:
    container_name: contest_mode_django
    image: ${DOCKER_REGISTRY_IMAGE}
    build:
      context: .
      dockerfile: Dockerfile.prod
    command: gunicorn brain.wsgi:application --bind 0.0.0.0:8000
    env_file:
      - ./.env.prod
    networks:
      - "contest_backend"
    volumes:
      - .:/usr/src/app/
    ports:
      - ${GUNICORN_PORT}:8000
    depends_on:
      - db
    environment:
      DEBUG: ${DEBUG}
      SECRET_KEY: ${SECRET_KEY}
      # DB
      DB_NAME: ${DB_NAME}
      DB_USERNAME: ${DB_USERNAME}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_HOST: ${DB_HOST}
      DB_PORT: ${DB_PORT}
      # PRAW
      PRAW_CLIENT_ID: ${PRAW_CLIENT_ID}
      PRAW_CLIENT_SECRET: ${PRAW_CLIENT_SECRET}
      PRAW_PASSWORD: ${PRAW_PASSWORD}
      PRAW_USERNAME: ${PRAW_USERNAME}
      PRAW_USER_AGENT: ${PRAW_USER_AGENT}

networks:
  contest_backend:
    driver: "bridge"

volumes:
  contest_mode_db_vol:
    external: true
