# Generated by Django 4.1.3 on 2022-11-27 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='submission',
            name='upvotes',
            field=models.IntegerField(default=0),
        ),
    ]
