# Generated by Django 4.1.3 on 2022-11-27 20:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0002_submission_upvotes'),
    ]

    operations = [
        migrations.AddField(
            model_name='submission',
            name='original_flair_template_id',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
    ]
