# Generated by Django 4.1.3 on 2022-11-27 21:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0003_submission_original_flair_template_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='submission',
            name='currently_promoted',
            field=models.BooleanField(default=False),
        ),
    ]
