# Generated by Django 4.1.3 on 2022-11-29 20:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0004_submission_currently_promoted'),
    ]

    operations = [
        migrations.AlterField(
            model_name='submission',
            name='title',
            field=models.CharField(max_length=1024),
        ),
    ]
